#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

ENV_FILE=".env.local"
TOTAL_STAGES=6

banner "googleAccountServiceList — Google OAuth セットアップ"

# ── Stage 1: プロジェクト作成 ──────────────────────────────────────────────
stage "Google Cloudプロジェクトを用意する"
say "このアプリがGoogleにサインインを許可してもらうための「箱」を1つ作ります。"
say "すでにこのアプリ用のプロジェクトがあるなら、それを選んでもOKです。"
open_url "https://console.cloud.google.com/projectcreate"
step "プロジェクト名に googleAccountServiceList のような分かりやすい名前を入れる"
step "「作成」を押す（数秒〜1分待つ場合があります）"
step "画面上部のプロジェクト選択メニューで、作成したプロジェクトが選ばれていることを確認する"
pause "プロジェクトを作成・選択できたら Enter"

# ── Stage 2: OAuth同意画面（基本情報） ─────────────────────────────────────
stage "OAuth同意画面を設定する（基本情報）"
say "「このアプリは何者か」をGoogleとユーザーに説明する画面です。"
open_url "https://console.cloud.google.com/apis/credentials/consent"
step "User Type は「外部（External）」を選ぶ（個人のGoogleアカウントを使うため）"
step "アプリ名: googleAccountServiceList"
step "ユーザーサポートメール: hib4ri.app.service@gmail.com"
step "デベロッパーの連絡先情報: hib4ri.app.service@gmail.com"
step "保存して次へ、を繰り返して先に進む"
note "公開ステータスは「テスト」のままにしてください（後続ステージでテストユーザーを登録します）"
pause "基本情報を入力できたら Enter"

# ── Stage 3: スコープ追加 ──────────────────────────────────────────────────
stage "同意画面にスコープを追加する"
say "アプリが取得を求める権限の一覧です。「スコープを追加または削除」ボタンから選びます。"
step "以下の4つを検索して追加する:"
note "  - .../auth/userinfo.email"
note "  - .../auth/userinfo.profile"
note "  - openid"
note "  - https://www.googleapis.com/auth/gmail.readonly"
warn "gmail.readonly は「制限付きスコープ」です。選択時に用途の説明を求められたら、"
warn "「利用者自身のGoogleアカウントに紐づく登録済みサービスを検出する、個人〜少人数向けの" \
     "ツールのため」のように書いてください。"
step "スコープを保存して先に進む"
pause "スコープを追加できたら Enter"

# ── Stage 4: テストユーザー登録 ────────────────────────────────────────────
stage "テストユーザーを登録する"
say "審査完了前は、ここに登録したGoogleアカウントしかサインインできません（最大100人）。"
step "「テストユーザーを追加」から、実際に使わせたい人のGoogleメールアドレスを追加する"
step "自分自身のメールアドレスも忘れずに追加する"
step "保存する"
pause "テストユーザーを登録できたら Enter"

# ── Stage 5: OAuthクライアントID作成 ───────────────────────────────────────
stage "OAuthクライアントIDを作成する"
say "アプリがGoogleと通信するための「鍵」を発行します。"
open_url "https://console.cloud.google.com/apis/credentials"
step "「認証情報を作成」→「OAuthクライアントID」を選ぶ"
step "アプリケーションの種類: 「ウェブ アプリケーション」"
step "名前: googleAccountServiceList (local dev) など分かりやすいものでOK"
step "「承認済みのリダイレクトURI」に次を追加する（本番ドメインは未確定のため、まずローカル用のみ）:"
note "  http://localhost:3000/api/auth/callback/google"
step "「作成」を押すと、クライアントIDとクライアントシークレットが表示される"
say "表示された値をここに貼り付けてください（この画面は閉じると再表示できないので注意）。"
ask AUTH_GOOGLE_ID "クライアントIDを貼り付け:"
ask_secret AUTH_GOOGLE_SECRET "クライアントシークレットを貼り付け:"
write_env AUTH_GOOGLE_ID "$AUTH_GOOGLE_ID"
write_env AUTH_GOOGLE_SECRET "$AUTH_GOOGLE_SECRET"

# ── Stage 6: AUTH_SECRET生成 ───────────────────────────────────────────────
stage "アプリ自身のセッション暗号化キーを作る"
say "こちらはGoogleではなく、このアプリ自身がセッションを暗号化するための鍵です。"
say "自動生成できます。以下のコマンドをこのターミナルとは別の場所（プロジェクトフォルダ）で"
say "一度だけ実行し、出てきた値を貼り付けてください:"
note "  npx auth secret"
note "（実行すると .env.local に AUTH_SECRET が自動追加されることがありますが、"
note "  このウィザードでも保存するので上書きされて問題ありません）"
ask_secret AUTH_SECRET "生成された値（または適当な長いランダム文字列）を貼り付け:"
write_env AUTH_SECRET "$AUTH_SECRET"

finish
note ".env.local はコミットされません（.gitignoreで除外済み）。"
note "この後 pnpm dev でローカル起動し、テストユーザーのGoogleアカウントでサインインを試してください。"
